name: Continuous Integration

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: make all

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Releases
        path: '**/*.dol'
